node{
  stage('SCM Checkout'){
  git 'https://github.com/srinivasreddii/Spring-Boot'
  }
  stage('SonarQube Analysis'){
    withSonarQubeEnv('Sonar'){
      bat 'mvn sonar:sonar'
    }  
  }
  stage('Compile and Package'){
  bat 'mvn package'
  }
  stage('Email Notification'){
  emailext body:  '''Jenkins build was successful.. :)

Thanks - Reddy''', subject: 'Jenkins Pipeline Build', to: 'sreenivasulu.g@slkgroup.com'
  }
   
}
